# -*- coding: utf-8 -*-
"""Copy_of_DSCI_454_Final_Project_Fatima_Hari_Ishan_Zayanna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zWMcykLedkdyqvOzQWvx-t_NDks9bIgS
"""

!pip install geoviews bokeh dash -q
!pip install -q panel hvplot jupyter_bokeh

import hvplot.pandas
import pandas as pd
import holoviews as hv
import panel as pn
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

pn.extension('bokeh', 'plotly', sizing_mode="stretch_width")

# ---------- LOAD & CLEAN ----------
url = "https://raw.githubusercontent.com/ingohel/Traffic-Accident-Data/df67b4529dfb96a439c10e9d852e08a0b11d07e8/US_Accidents_sampled_100k.csv.gz"
df = pd.read_csv(url, compression="gzip")

df = df.dropna(subset=['Start_Lat', 'Start_Lng'])
df['City'] = df['City'].fillna('Unknown')
df['State'] = df['State'].fillna('Unknown')
df['Weather_Condition'] = df['Weather_Condition'].fillna('Unknown')
df['Temperature(F)'] = df['Temperature(F)'].fillna(0)
df['Visibility(mi)'] = df['Visibility(mi)'].fillna(0)
df['Severity'] = df['Severity'].fillna(2).astype(int)

labels = {1: '1 - Minor', 2: '2 - Moderate', 3: '3 - Serious', 4: '4 - Critical'}
df['Severity Label'] = df['Severity'].map(labels)

df["Start_Time"] = pd.to_datetime(df["Start_Time"], format="mixed", errors="coerce")
df = df.dropna(subset=["Start_Time"])
df["Year"] = df["Start_Time"].dt.year
df["Hour"] = df["Start_Time"].dt.hour
day_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
df["Day"] = pd.Categorical(df["Start_Time"].dt.day_name(), categories=day_order, ordered=True)

# ---------- GLOBAL WIDGETS (sidebar) ----------
severity_widget = pn.widgets.MultiChoice(
    name="Severity",
    value=[1, 2, 3, 4],
    options=[1, 2, 3, 4]
)

state_widget = pn.widgets.MultiChoice(
    name="State",
    value=[],  # empty = all
    options=sorted(df['State'].unique().tolist()),
    placeholder="All states"
)

year_widget = pn.widgets.IntRangeSlider(
    name="Year Range",
    start=int(df['Year'].min()),
    end=int(df['Year'].max()),
    value=(2017, 2022),
    step=1
)

# ---------- FILTERED DATA (reactive) ----------
def filter_df(severity, states, year_range):
    filtered = df[df['Severity'].isin(severity)]
    filtered = filtered[(filtered['Year'] >= year_range[0]) & (filtered['Year'] <= year_range[1])]
    if states:
        filtered = filtered[filtered['State'].isin(states)]
    return filtered

# ---------- CHARTS (all reactive to widgets) ----------
def plot_map(severity, states, year_range):
    d = filter_df(severity, states, year_range)
    if len(d) == 0:
        return pn.pane.Markdown("### No data matches filters")
    sample = d.sample(n=min(20000, len(d)), random_state=42)
    fig = px.scatter_mapbox(
        sample, lat='Start_Lat', lon='Start_Lng', color='Severity',
        color_continuous_scale=['green', 'yellow', 'orange', 'red'],
        zoom=3, height=450,
        hover_data=['City', 'State', 'Weather_Condition']
    )
    fig.update_traces(marker=dict(size=4, opacity=0.6))
    fig.update_layout(mapbox_style='carto-darkmatter', margin=dict(l=0, r=0, t=10, b=0),
                      paper_bgcolor='rgba(0,0,0,0)')
    return pn.pane.Plotly(fig, sizing_mode="stretch_width", height=450)

def plot_yearly(severity, states, year_range):
    d = filter_df(severity, states, year_range)
    yearly = d.groupby("Year").size().reset_index(name="Count")
    fig, ax = plt.subplots(figsize=(7, 3.5))
    sns.lineplot(data=yearly, x="Year", y="Count", marker="o", linewidth=2, ax=ax, color='#E74C3C')
    ax.set_title("Accidents Per Year")
    ax.grid(alpha=0.3)
    plt.tight_layout()
    plt.close(fig)
    return pn.pane.Matplotlib(fig, tight=True, sizing_mode="stretch_width")

def plot_kde(severity, states, year_range):
    d = filter_df(severity, states, year_range).dropna(subset=["Sunrise_Sunset"])
    fig, ax = plt.subplots(figsize=(7, 3.5))
    if len(d) > 0:
        sns.kdeplot(data=d, x="Severity", hue="Sunrise_Sunset",
                    fill=True, common_norm=False, alpha=0.5, ax=ax)
    ax.set_title("Severity: Day vs Night")
    plt.tight_layout()
    plt.close(fig)
    return pn.pane.Matplotlib(fig, tight=True, sizing_mode="stretch_width")

def plot_weather(severity, states, year_range):
    d = filter_df(severity, states, year_range)
    top = d['Weather_Condition'].value_counts().head(10)
    fig = px.bar(x=top.index, y=top.values,
                 labels={'x': 'Weather', 'y': 'Accidents'},
                 color=top.values, color_continuous_scale='Reds')
    fig.update_layout(height=400, margin=dict(l=10, r=10, t=30, b=10),
                      title="Top 10 Weather Conditions",
                      paper_bgcolor='rgba(0,0,0,0)', showlegend=False,
                      coloraxis_showscale=False)
    return pn.pane.Plotly(fig, sizing_mode="stretch_width", height=400)

def plot_heatmap(severity, states, year_range):
    d = filter_df(severity, states, year_range)
    heatmap_data = d.groupby(["Day", "Hour"], observed=True).size().reset_index(name="Count")
    return heatmap_data.hvplot.heatmap(
        x="Hour", y="Day", C="Count", cmap="Reds",
        height=400, responsive=True, title="Accidents by Day & Hour"
    )

# ---------- BIND WIDGETS TO PLOTS ----------
deps = dict(severity=severity_widget, states=state_widget, year_range=year_widget)

map_pane = pn.bind(plot_map, **deps)
yearly_pane = pn.bind(plot_yearly, **deps)
kde_pane = pn.bind(plot_kde, **deps)
weather_pane = pn.bind(plot_weather, **deps)
heatmap_pane = pn.bind(plot_heatmap, **deps)

# ---------- KPI CARDS ----------
def make_kpis(severity, states, year_range):
    d = filter_df(severity, states, year_range)
    total = pn.indicators.Number(name="Total Accidents", value=len(d),
                                  format="{value:,}", font_size="28pt", title_size="14pt")
    avg_sev = pn.indicators.Number(name="Avg Severity", value=round(d['Severity'].mean(), 2) if len(d) else 0,
                                    font_size="28pt", title_size="14pt")
    states_n = pn.indicators.Number(name="States", value=d['State'].nunique(),
                                     font_size="28pt", title_size="14pt")
    return pn.Row(total, avg_sev, states_n)

kpi_pane = pn.bind(make_kpis, **deps)

# sidebar styled like FastListTemplate
sidebar = pn.Column(
    pn.pane.Markdown("## 🚗 Dashboard\n### Filters", styles={'color': 'white'}),
    severity_widget,
    state_widget,
    year_widget,
    width=280,
    styles={'background': '#2C3E50', 'padding': '20px', 'color': 'white'},
    height=900
)

# main content area
main = pn.Column(
    pn.pane.Markdown("# US Traffic Accidents Dashboard",
                     styles={'background': '#2C3E50', 'color': 'white', 'padding': '15px'}),
    kpi_pane,
    pn.Card(map_pane, title="Accident Locations"),
    pn.Row(
        pn.Card(yearly_pane, title="Yearly Trend"),
        pn.Card(kde_pane, title="Day vs Night"),
    ),
    pn.Row(
        pn.Card(weather_pane, title="Weather Conditions"),
        pn.Card(heatmap_pane, title="Time Heatmap"),
    ),
    sizing_mode="stretch_width"
)

dashboard = pn.Row(sidebar, main)
dashboard